### ISSUE TITLE
关于Patch-GCN

### ISSUE THREAD

**Issue by ljhOfGithub** [liupei101/DSCA#1]
您好，很棒的工作！我在您的论文里面看到复现了patch-gcn的结果，请问您在复现patch-gcn的时候有没有过这种bug：
keys = list(set(data_list[0].keys) - set(exclude_keys))
AttributeError: 'Tensor' object has no attribute 'keys'
如果有的话，您当时是怎么解决的。
如果没有的话，请问您当时是怎么提取的wsi文件的特征，我是先用CLAM的create_patches_fp.py分割patch，然后使用extract_features_fp.py提取特征，最终产生了.h5文件和.pt文件，但是我发现源代码中在dataset_survial.py中的260行左右，使用了wsi_bag = torch.load(wsi_path)载入pt文件，但是我的wsi_bag的类型是一个Tensor矩阵，不是字典，在BatchWSI.py的第28行左右，keys = list(set(data_list[0].keys) - set(exclude_keys))，由于data_list[0]是一个list，导致无法获取keys，所以这里报了如上所述的错误，请问您当时处理到这一步的时候的数据类型是什么？
因为我联系不到Patch-GCN的作者，如果可以的话，请您帮我看看这个问题，非常感谢。

**Comment by liupei101** [comment]
您好，感谢您对我们工作的关注。

我们在复现PatchGCN时，没有遇到这种问题。我们是首先用CLAM提取到patch特征，然后按照[文档](https://github.com/mahmoodlab/Patch-GCN/blob/master/WSI-Graph%20Construction.ipynb) 构建patch图。构建Patch图的代码中是添加了一些keys的，或许您需要核对下构建patch图的文档。
